### ISSUE TITLE
代码的可阅读性

### ISSUE THREAD

**Issue by likeAwind** [hcSomething/virtualProject#10]
![image](https://user-images.githubusercontent.com/11746765/48684512-def1d500-ebec-11e8-8fb4-dbf3fbbac7e7.png)
该段代码的可阅读性是否不太友好。
例如 int isalive = monster.canAttack( skillId, player);
canAttack方法名传递出的信息 应该返回的是boolean 判断是否应该可以攻击。但是实际它的作用不是这样的。
isalive 如果换成面向对象编程中的 枚举 该段代码的可阅读性是否可以提高很多？
类似的问题在该项目的其它地方是不是也经常出现？

**Comment by hcSomething** [comment]
出现这个问题是因为，定义这个方法和变量名的时候代码不是这样实现的，后来改变实现方式时，没有改变相应的方法名。以后注意。

**Comment by likeAwind** [comment]
代码的 变量名 方法名 类名 都是非常重要的信息.再团队合作中非常重要.不然对方使用错了你的接口.后果非常严重的.
所以这点一定要重视. 
关于详细的规则可以参见 《重构》 《代码大全》 《代码整洁之道》等书

**Comment by hcSomething** [comment]
好的
