### ISSUE TITLE
成就系统可扩展性和神秘数值

### ISSUE THREAD

**Issue by likeAwind** [hcSomething/virtualProject#11]
![image](https://user-images.githubusercontent.com/11746765/48689662-76afed00-ec06-11e8-804e-18f2bea8374a.png)
任务和成就系统。策划往往会经常 增加新类型 修改数值 等操作。
这样直接在代码中写死数据 是不是不太好？这些东西应该放到配置表中配置。

![image](https://user-images.githubusercontent.com/11746765/48689762-dc9c7480-ec06-11e8-96dd-98f3574979b9.png)

如果策划添加新的成就。还需要告知开发人员修改数据库字段。这样扩展性会不会太差了?

**Comment by hcSomething** [comment]
已经修改了成就系统的实现，使得成就实体和任务实体类似的实现。

**Comment by likeAwind** [comment]
重构完了 提交。并且close这个议题
