### ISSUE TITLE
对于IO操作的业务都需要谨慎考虑性能问题。

### ISSUE THREAD

**Issue by likeAwind** [hcSomething/virtualProject#12]
/**
	 * 获得数据库中，最大的id
	 * 从而在服务器，关闭，开启的时候，获得一个目前最大的id，来给新注册的玩家用
	 */
	public int getMaxId() {
		String hql = "select pe from PlayerEntity pe";
		List<PlayerEntity> pes = new PlayerDaoImpl().find(hql);
		int result = 0;
		for(PlayerEntity p : pes) {
			if(p.getId() > result)
				result = p.getId();
		}
		return result + 1;
	}

生产环境下player表可能高达几个G。
这个操作不会把内存load爆么!?

一般情况下 对于IO操作的业务都需要谨慎考虑性能问题。
类似的问题：
例如 如果场景线程 被IO阻塞了会出现什么问题？

**Comment by hcSomething** [comment]
修改为
public int getMaxId() {
		String hql = "select max(pe.id) from PlayerEntity pe";
		List<Integer> pes = new PlayerDaoImpl().find(hql);
		int result = pes.get(0);
		return result + 1;
}

**Comment by hcSomething** [comment]
场景线程被阻塞了会很严重。阻塞之后场景心跳就没有了，所有在当前场景中的玩家的操作都不能进行。
