### ISSUE TITLE
TaskConsume线程资源

### ISSUE THREAD

**Issue by likeAwind** [hcSomething/virtualProject#2]
public void run() {
		if(isActive.compareAndSet(false, true)) {
			ScheduledExecutorService service = Executors.newSingleThreadScheduledExecutor();
			Future future = service.scheduleAtFixedRate(this, 5, eInterval.get(), TimeUnit.SECONDS);
			if(taskId.length() > 5 && taskId.substring(0, 5).equals("copys")) {
				Context.getWorld().getFutureMap().put(taskId, future);
			}
			if(taskId.length() > 4 && taskId.substring(0, 4).equals("boss")) {
				Context.getWorld().getFutureMap().put(taskId, future);
			}
			if(taskId.length() > 6 && taskId.substring(0, 6).equals("summon")) {
				Context.getWorld().getFutureMap().put(taskId, future);
			}
		}
		execute();		
	}

线程资源是非常宝贵的。通常合理的游戏 逻辑线程数量是不得超过cpu核数*2（IO任务线程除外）.
这样一个领域对象就申请一个线程池？ 当游戏在线人数多的时候 几百上千个领域对象时。线程数量是否爆炸？

**Comment by hcSomething** [comment]
TaskConsume不用Executors.newSingleThreadExecutor而用Excutors.newScheduledThreadPool(),
所有需要有周期性任务类都不再继承TaskConsume类，而是实现Runnalbe，
然后用schedule.schedule()来启动任务的执行。
