### ISSUE TITLE
商店购买参数验证

### ISSUE THREAD

**Issue by likeAwind** [hcSomething/virtualProject#3]
/**
	 * 购买物品，并验证当前商店页面是否有此物品
	 * @param session
	 * @param gid
	 * @param amount
	 */
	public void validBuyGood(Session session, int gid, int amount) {
		if(session.getPlayer().getPageNumber() == 0) {
			session.sendMessage("当前还不在商店页面，请先进入商店");
			return;
		}
		Store store = Context.getStore();
		//验证要购买的商品是否在这个商店页面
		boolean within = store.withinPage(session.getPlayer(), gid);
		if(!within) {
			session.sendMessage("您要购买的商品不在当前列表中，请检查参数是否正确！");
			return;
		}
		if(amount > 100) {
			session.sendMessage("购买失败，一次只能购买100件相应物品");
			return;
		}
		boolean hasbuy = store.buyGood(session.getPlayer(), gid, amount);
		if(!hasbuy) session.sendMessage("购买失败，请检查是否有足够的金币");
		else session.sendMessage("购买成功");
	}

这里是否包含 amount <= 0 的判断？

**Comment by hcSomething** [comment]
对于小于0的情况，在Order中进行了验证
