### ISSUE TITLE
WorldChat 线程安全

### ISSUE THREAD

**Issue by likeAwind** [hcSomething/virtualProject#4]
@Component
public class WorldChat {

	//一定大小的聊天记录，只记录最新的三十条记录，超过就删除最旧的记录
	private Vector<String> records = new Vector<>(30);
	
	/**
	 * 添加聊天记录。添加之后要推送给所有进入世界聊天的玩家
	 * @param msg
	 */
	synchronized public void addRecord(String msg) {
		if(records.size() < 30) {
			records.add(0, msg);
		}else {
			records.remove(records.size()-1);
			records.add(0, msg);
		}
		//通知所有进入世界频道的玩家
		Context.getWorldChatObservable().setMsg(msg);
	}
	
	
	//得到最新的一条记录
	public String getupdate() {
		return records.get(0);
	}
	
	/**
	 * 获得当前所有聊天记录
	 * @return
	 */
	public Vector<String> getRecords(){
		return records;
	}
	
}

Vector因为性能低下已经被jdk废弃，如果想使用线程安全的集合请使用 并发包下面的 CopyOnWriteArrayList。

synchronized public void addRecord(String msg)  加上 Vector 这两个并发的条件是否能够确保 集合的并发安全？

**Comment by hcSomething** [comment]
当初用vector的目的是为了实现聊天内容按时间逆序排列，从而最新的数据在最前面，但实际上也没有这样做。
不一定是线程安全的，调用getRecodrs()方法可能会出现异常。
