### ISSUE TITLE
线程安全

### ISSUE THREAD

**Issue by likeAwind** [hcSomething/virtualProject#5]
public List<UnionEntity> getUnionEntity(){
		return unionEntitys;
	}
	/**
	 * 创建工会
	 * @param uname
	 * @param pname
	 * @return
	 */
	public boolean createUnion(String uname, String pname) {
		lock.lock();
		try {
			if(getUnionEntityByName(uname) != null) {
				return false;
			}
			UnionEntity ue = new UnionEntity(uname, pname);
			unionEntitys.add(ue);
			new PlayerDaoImpl().insert(ue);  //插入数据库
			return true;
		}finally {
			lock.unlock();
		}
	}

unionEntitys 这样书写是否还是会出现 并发失败问题？

**Comment by hcSomething** [comment]
会出现错误，在getUnionEntity()方法中加上同步方法，并且返回的是一个新的list

**Comment by likeAwind** [comment]
这样做可以。只不过非常耗费性能。同时也只能说保证了unionEntitys 集合本身的线程安全。内部元素的数据的安全性是无法保证的。
所以遇到需要共享的公共数据时 如何保证数据安全且保证性能是非常困难的问题。
详细可以参见 《Java并发编程实战》这本书
