### ISSUE TITLE
内存占用缓存问题

### ISSUE THREAD

**Issue by likeAwind** [hcSomething/virtualProject#6]
//所有注册的玩家，
	private List<Player> allRegisteredPlayer = new ArrayList<>();

通常一个游戏服有1W注册量，但是在后期同时在线的玩家可能不足200人。讲所有玩家数据都缓存在内存中 是否对内存浪费过于严重？

**Comment by hcSomething** [comment]
allRegisteredPlayer这个字段是为了解决重复注册的问题，只有在注册时有被调用，其他时候没有用，因此可以在玩家登陆后，就删除相应的数据

**Comment by likeAwind** [comment]
![image](https://user-images.githubusercontent.com/11746765/48748135-c0eda880-ecb0-11e8-99ad-e984782df3e3.png)
//所有玩家实体，在启动时，从数据库加载 这个所有玩家实体数据量也太大了！！！

**Comment by likeAwind** [comment]
提示：结合我们现网的项目 看看是如何处理的。

**Comment by hcSomething** [comment]
现网中，玩家实体的数据只有在创建新玩家和需要玩家实体时，才会创建或者从数据库查询，并缓存。
并且这个缓存的容量是有限制的。
在玩家删除角色时，会从缓存中删除。

**Comment by likeAwind** [comment]
现网中应用了 google的 支持LRU算法的集合。 再者应用了软引用 和 弱引用相关的技术 你可以下去了解也一下相关的技术点。
