### ISSUE TITLE
做一个小练习，写一个线程死锁的小程序

### ISSUE THREAD

**Issue by likeAwind** [hcSomething/virtualProject#7]
刻意构建出一个线程死锁的演示代码。

**Comment by hcSomething** [comment]
public class DeadLockTest {

	public static void main(String[] args) {
		TaskA ta = new TaskA("a");
		TaskA tb = new TaskA("b");
		
		ThreadA threada = new ThreadA(ta, tb);
		ThreadA threadb = new ThreadA(tb, ta);
		threada.start();
		threadb.start();
		
		System.out.println("开始工作");
	}
}


public class TaskA {

	private String name;
	private int inUse = 0;
	
	public TaskA(String name) {
		this.name = name;
	}
	
	synchronized public void doTask() {
		try {
			if(inUse == 1) {
				System.out.println("进入睡眠" + Thread.currentThread());
				wait();
			}
			setInUse(1);
			System.out.println(name + " 开始这部分工作 " + Thread.currentThread());
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
	}
	
	synchronized public void taskComp() {
		setInUse(0);
		setInUse(0);
		notifyAll();
	}

	
	public void myName() {
		System.out.println("当前工作的名字：" + name);
	}
	synchronized public int getInUse() {
		return inUse;
	}

	synchronized public void setInUse(int inUse) {
		this.inUse = inUse;
	}
	
}


public class ThreadA extends Thread{

	private TaskA taska;
	private TaskA taskb;
	Object a = new Object();
	
	public ThreadA(TaskA a, TaskA b) {
		this.taska = a;
		this.taskb = b;
	}
	
	public void run() {
		while(true) {
			System.out.println("threadA----");
			taska.doTask();			
			taskb.doTask();
			taska.taskComp();
		}
	}
}


就会出现死锁

**Comment by likeAwind** [comment]
这个是一个阻塞型死锁. 还有一种 叫相互等待型死锁("哲学家就餐问题"). 后者比较难以发现 危险性更大? 写出来 然后思考一下如何避免出现死锁的问题.

**Comment by hcSomething** [comment]
public class PhilosopherTest {

	public static void main(String[] args) {
		int size = 5;
		Chopstick[] chopsticks = new Chopstick[size];
		for(int i = 0; i < size; i++) {
			chopsticks[i] = new Chopstick();
		}
		for(int i = 0; i < size; i++) {
			new Philosopher(chopsticks[i], chopsticks[(i+1)%size], i).start();
		}
		
	}
}


public class Chopstick {
	
	private boolean taken = false;
	
	public synchronized void take(int id) throws InterruptedException {
		while(taken) {
			wait();
		}
		taken = true;
	}
	
	public synchronized void drop() {
		taken = false;
		notifyAll();
	}
}


public class Philosopher extends Thread{

	private Chopstick left;
	private Chopstick right;
	private int id;
	
	public Philosopher(Chopstick left, Chopstick right, int id) {
		this.left = left;
		this.right = right;
		this.id = id;
	}
	
	public void run() {
		while(true) {
			try {
				System.out.println(id + "开始思考");
				Thread.sleep(50);
				System.out.println(id + "准备吃饭");
				System.out.println(id + "拿起右边的筷子");
				right.take(id);
				System.out.println(id + "拿起左边的筷子");
				left.take(id);
				System.out.println(id + "开始吃饭");
				int a = (int)Math.random()*1000+2000;
				Thread.sleep(a);
				right.drop();
				left.drop();
			} catch (InterruptedException e) {				
				e.printStackTrace();
			}
			
		}
	}	
}

死锁发生的条件：1、互斥性，一个资源只能被一个任务拥有
                              2、至少有一个任务是在拥有了一个资源后，还请求另一个资源。
                             3、资源只能由任务拥有者自己释放
                             4、出现一个资源依赖循环
因此，只要能破环任一个条件，就可以避免死锁的出现。

**Comment by likeAwind** [comment]
目前这个项目中也大量使用了锁，这个项目的实际开发 结合 上面的理论 有哪些手段可以避免死锁的产生?

**Comment by hcSomething** [comment]
目前使用锁的目的是为了保证公共资源，比如公会物品，怪物最后一击等等，
可以通过避免获得了某个锁之后，还要获得另外的锁来破环条件2。
