### ISSUE TITLE
玩家消息处理的有序性

### ISSUE THREAD

**Issue by likeAwind** [hcSomething/virtualProject#8]
@Override
	public void channelRead(ChannelHandlerContext ctx, Object msg) {
		ByteBuf mesg = (ByteBuf)msg;
		String order = "";
		try {
			order = EncodeAndDecode.decode(mesg);
			System.out.println("服务端接收到的信息为：" + order);
		} catch (Exception e) {
			e.printStackTrace();
		}
		
		//解析命令
		String[] st = order.split(" ");

		Order.getService(st, Context.getSessionByChannel(ctx.channel()));
		

	}

通过这种方式能否避免玩家的消息是有序处理的？
比如一个玩家正在操作自己的背包 整理排序。 然后紧接着对背包进行下一次操作。比如合成
背包是否有可能在 整理的过程中 同时执行其它操作。 那么这样会不会有很大风险？

**Comment by hcSomething** [comment]
netty同一个客户端发出的指令，不一定是在同一个线程中执行的。
如果是在同一个线程中执行的，那么肯定是先后执行的
如果是两个线程都想对背包进行操作，可以通过加锁的方法来解决

**Comment by likeAwind** [comment]
如果是针对玩家自己的数据也需要通过加锁来解决.这样几乎所有的系统都需要加锁了. 这样编码难度 和 代码的复杂度会不会极大的增加?
有没有一种简单的方式 改变玩家的线程模型来解决 玩家自己的线程安全问题?  (可以参考现网游戏项目)

**Comment by hcSomething** [comment]
现网游戏中利用了场景心跳，将所有和玩家相关的包都在player对象中处理，从而保证了消息的顺序。
利用这种方法，将玩家输入的命令都放在player的一个队列中，顺序处理
