### ISSUE TITLE
netty的断开连接

### ISSUE THREAD

**Issue by likeAwind** [hcSomething/virtualProject#9]
![image](https://user-images.githubusercontent.com/11746765/48683892-32165880-ebea-11e8-9a4e-514c8632c284.png)
当客户端强制断开连接时会触发exceptionCaught。
但是当客户端如果是正常close连接时。并不会触发exceptionCaught。那么断开连接的处理是否会遗漏？

**Comment by hcSomething** [comment]
目前还没有玩家主动断开连接的指令，所有的断开都是强制性的。
可以增加主动断开的功能
